services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 5010
    command: >
      sh -c "
        node ace migration:run &&
        node ace serve --watch
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - '3090:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
