services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5010:5010'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 5010
    command: ['node', 'ace', 'serve', '--watch']